# Generated by Django 4.2.1 on 2023-06-26 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='id_cliente')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='apellido')),
                ('correo', models.CharField(max_length=20, verbose_name='correo')),
                ('telefono', models.CharField(max_length=20, verbose_name='telefono')),
                ('comuna', models.CharField(max_length=20, verbose_name='comuna')),
                ('ciudad', models.CharField(max_length=20, verbose_name='ciudad')),
                ('region', models.CharField(max_length=20, verbose_name='region')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio', models.CharField(max_length=20, verbose_name='tipo_envio')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_envio', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='id_envio')),
                ('fecha_envio', models.DateField(verbose_name='fecha_envio')),
                ('valor_envio', models.CharField(max_length=20, verbose_name='valor_envio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('tipo_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.envio')),
            ],
        ),
    ]
